services:
  db:
    image: mysql:9.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASS}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
